env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  object-curly-newline:
    [
      error,
      {
        ObjectExpression: { consistent: true, multiline: true },
        ObjectPattern: { consistent: true, multiline: true },
        ImportDeclaration: never,
        ExportDeclaration: never,
      },
    ]
  react/function-component-definition:
    [
      error,
      { namedComponents: arrow-function, unnamedComponents: arrow-function },
    ]
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: [warn, { extensions: [".js", ".jsx"] }]
