export const METADATA_SCHEMA = {
  title: 'Tissue Block',
  columns: {
    sample_ID: {
      label: 'sample_ID',
      type: 'text',
      required: true,
      description: 'The HuBMAP ID for the sample assigned by the ingest portal. An example value might be "HBM743.CKJW.876".',
    },
    source_storage_time_value: {
      label: 'source_storage_time_value',
      type: 'number',
      required: true,
      description: 'How long was the source material stored, prior to this sample being processed? For tissue blocks, this would typically be the time between when the organ arrived in the lab and the processing of the organ began. In most cases this will likely be 0, while in some cases the organ might be stored (on ice) in the lab before dissection. For tissue sections, this would be how long the tissue block was stored, usually in a -80 freezer, prior to the section being cut. For suspensions, this would be the length of time the tissue block was stored prior to the initiation of the dissociation process.',
    },
    source_storage_time_unit: {
      label: 'source_storage_time_unit',
      type: 'text',
      permissibleValues: [{
        label: 'minute',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000031',
      }, {
        label: 'hour',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000032',
      }, {
        label: 'day',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000032',
      }, {
        label: 'year',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000036',
      }],
      required: true,
      description: 'Time unit',
    },
    preparation_medium: {
      label: 'preparation_medium',
      type: 'text',
      permissibleValues: [{
        label: 'PFA 4%',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/PFA4pc-prep',
      }, {
        label: 'Buffered Formalin (10% NBF)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/bufferedFormalin-10pcNBF-prep',
      }, {
        label: 'Non-Buffered Formalin (FOR)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/Non-BufferedFormalin-FOR-prep',
      }, {
        label: '1 x PBS',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/1xPBS-prep',
      }, {
        label: 'OCT',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/OCT',
      }, {
        label: 'CMC',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/CMC-prep',
      }, {
        label: 'MACS Tissue Storage Solution',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/maCSTissueStorageSolution-prep',
      }, {
        label: 'RNALater',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C63348',
      }, {
        label: 'Methanol',
        meaning: 'http://purl.bioontology.org/ontology/MESH/D000432',
      }, {
        label: 'Non-Aldehyde Based Without Acetic Acid (NAA)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/Non-AldehydeBasedWithoutAceticAcid-NAA',
      }, {
        label: 'Non-Aldehyde With Acetic Acid (ACA)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/Non-AldehydeWithAceticAcid-ACA',
      }, {
        label: 'PAXgene Blood Tissue System',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C126392',
      }, {
        label: 'Allprotect Tissue Reagent (ALL)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/allprotectTissueReagent-ALL-prep',
      }, {
        label: 'None',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41132',
      }],
      required: true,
      description: 'The medium used during preparation of the sample.',
    },
    preparation_temperature: {
      label: 'preparation_temperature',
      type: 'text',
      permissibleValues: [
        {
          label: 'Liquid Nitrogen',
          meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C68796',
        },
        {
          label: 'Liquid Nitrogen Vapor',
          meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C174159',
        },
        {
          label: 'Dry Ice',
          meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C63373',
        },
        {
          label: '4 Degrees Celsius',
          meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C185332',
        },
        {
          label: '24 Celsius (Room Temperature)',
          meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/24Celsius-RoomTemperature',
        },
        {
          label: '37 Celsius',
          meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/37Celsius-PT',
        },
        {
          label: 'Minus 80 Degrees Celsius',
          meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C185336',
        },
        {
          label: 'Minus 20 Degrees Celsius',
          meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C185334',
        }],
      required: true,
      description: 'The temperature for the preparation process.',
    },
    processing_time_value: {
      label: 'processing_time_value',
      type: 'number',
      required: true,
      description: 'How long was the tissue being handled before the initial preservation? For tissue blocks, this would typically be the length of time from when the organ was received in the lab to when the tissue block is frozen or otherwise preserved (e.g., imbedded in OCT). For a tissue section this would be how long it takes to slice the tissue block and fix the mounted slice, after removing the tissue block from the freezer. For a suspension this would be the length of time from when the tissue block is removed from the freezer, dissociated and processed to the point where by the suspension is put into the initial preservation buffer.',
    },
    processing_time_unit: {
      label: 'processing_time_unit',
      type: 'text',
      permissibleValues: [{
        label: 'minute',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000031',
      }, {
        label: 'hour',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000032',
      }, {
        label: 'day',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000032',
      }],
      required: true,
      description: 'Time unit.',
    },
    storage_medium: {
      label: 'storage_medium',
      type: 'text',
      permissibleValues: [{
        label: 'PFA 4%',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/PFA4pc-store',
      }, {
        label: 'Buffered Formalin (10% NBF)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/BufferedFormalin-10pcNBF',
      }, {
        label: 'Non-Buffered Formalin (FOR)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/Non-BufferedFormalin-FOR',
      }, {
        label: '1 x PBS',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/1xPBS-store',
      }, {
        label: 'OCT Embedded',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/OCTEmbedded',
      }, {
        label: 'CMC Embedded',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/CMCEmbedded',
      }, {
        label: 'OCT Embedded Cryoprotected (sucrose)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/OCTEmbeddedCryoprotected-sucrose',
      }, {
        label: 'Paraffin Embedded',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/ParaffinEmbedded',
      }, {
        label: 'MACS Tissue Storage Solution',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/mACSTissueStorageSolution',
      }, {
        label: 'RNALater',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C63348',
      }, {
        label: 'Methanol',
        meaning: 'http://purl.bioontology.org/ontology/MESH/D000432',
      }, {
        label: 'Tris-EDTA',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/Tris-EDTA',
      }, {
        label: '70% Ethanol',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/70pcEthanol',
      }, {
        label: 'Serum + DMSO',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/SerumplusDMSO',
      }, {
        label: 'DMSO (No serum)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/DMSO-Noserum',
      }, {
        label: 'PAXgene Blood Tissue System',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C126392',
      }, {
        label: 'Allprotect Tissue Reagent (ALL)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/allprotectTissueReagent-ALL',
      }, {
        label: 'Sucrose Cryoprotection Solution',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/SucroseCryoprotectionSolution',
      }, {
        label: 'CMC',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/CMC-store',
      }, {
        label: 'None',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C41132',
      }],
      required: true,
      description: 'What was the sample preserved in.',
    },
    storage_temperature: {
      label: 'storage_temperature',
      type: 'text',
      permissibleValues: [{
        label: 'Liquid Nitrogen (Unspecified)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/LiquidNitrogen-Unspecified',
      }, {
        label: 'Liquid Nitrogen (Cryotube)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/LiquidNitrogen-Cryotube',
      }, {
        label: 'Liquid Nitrogen (Straw)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/LiquidNitrogen-Straw',
      }, {
        label: 'Liquid Nitrogen Vapor',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C174159',
      }, {
        label: 'Dry Ice',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C63373',
      }, {
        label: '-80 Celsius (Unspecified)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/-80Celsius-Unspecified',
      }, {
        label: '-80 Celsius (Cryotube)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/-80Celsius-Cryotube',
      }, {
        label: '-80 Celsius (Straw)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/-80Celsius-Straw',
      }, {
        label: '4 Degrees Celsius',
        meaning: 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C185332',
      }, {
        label: '24 Celsius (Room Temperature)',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/24Celsius-RoomTemperature',
      }, {
        label: '37 Celsius',
        meaning: 'https://purl.org/hubmapvoc/samples-voc-additions/37Celsius-ST',
      }],
      required: true,
      description: 'The temperature during storage, after preparation and before the assay is performed.',
    },
    quality_criteria: {
      label: 'quality_criteria',
      type: 'text',
      required: false,
      description: 'For example, RIN: 8.7. For suspensions, measured by visual inspection prior to cell lysis or defined by known parameters such as wells with several cells or no cells. This can be captured at a high level. "OK" or "not OK", or with more specificity such as "debris", "clump", "low clump".',
    },
    histological_report: {
      label: 'histological_report',
      type: 'text',
      required: false,
      description: 'histopathological reporting of key variables that are important for the tissue (absence of necrosis, comment on composition, significant pathology description, high level inflammation/fibrosis assessment, etc.)',
    },
    thickness_value: {
      label: 'thickness_value',
      type: 'number',
      required: true,
      description: 'Thickness of a tissue section',
    },
    thickness_unit: {
      label: 'thickness_unit',
      type: 'text',
      permissibleValues: [{
        label: 'micrometer',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000017',
      }, {
        label: 'millimeter',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000016',
      }, {
        label: 'centimeter',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000015',
      }],
      required: true,
      description: 'Thickness unit',
    },
    section_index_number: {
      label: 'section_index_number',
      type: 'number',
      required: true,
      description: 'The index number for the section if the sample is a single section.',
    },
    area_value: {
      label: 'area_value',
      type: 'number',
      required: false,
      description: 'The area of a tissue section.',
    },
    area_unit: {
      label: 'area_unit',
      type: 'text',
      permissibleValues: [{
        label: 'mm^2',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000082',
      }, {
        label: 'um^2',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000082',
      }],
      required: false,
      description: 'Area unit',
    },
    notes: {
      label: 'notes',
      type: 'text',
      required: false,
      description: 'Researcher note',
    },
  },
};

export const METADATA_RECORDS = [
  {
    _id: 0,
    sample_ID: 'Visium_9OLC_A4_S1',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '-20 Celsius',
    processing_time_value: 4,
    processing_time_unit: 'min',
    storage_medium: 'OCT Embedded',
    storage_temperature: '-80 Celsius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: '_m',
    section_index_number: 2,
    area_value: 12.24,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 1,
    sample_ID: 'Visium_9OLC_A4_S2',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '-20 Celsius',
    processing_time_value: 4,
    processing_time_unit: 'min',
    storage_medium: 'OCT Embedded',
    storage_temperature: '-80 Celsius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: '_m',
    section_index_number: 3,
    area_value: 11.68,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 2,
    sample_ID: 'Visium_9OLC_I4_S1',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '-20 Celsius',
    processing_time_value: 4,
    processing_time_unit: 'min',
    storage_medium: 'OCT Embedded',
    storage_temperature: '-80 Celsius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: '_m',
    section_index_number: 2,
    area_value: 17.42,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 3,
    sample_ID: 'Visium_9OLC_I4_S2',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '-20 Celsius',
    processing_time_value: 4,
    processing_time_unit: 'min',
    storage_medium: 'OCT Embedded',
    storage_temperature: '-80 Celsius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: '_m',
    section_index_number: 3,
    area_value: 15.84,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 4,
    sample_ID: 'Visium_10CC_A2_S1',
    source_storage_time_value: '86 day',
    source_storage_time_unit: '',
    preparation_medium: 'Formalin',
    preparation_temperature: '',
    processing_time_value: '10 minutes',
    processing_time_unit: '',
    storage_medium: 'Paraffin',
    storage_temperature: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'millimeter',
    section_index_number: 1,
    area_value: 12.05,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 5,
    sample_ID: 'Visium_10CC_A2_S2',
    source_storage_time_value: '86 day',
    source_storage_time_unit: '',
    preparation_medium: 'Formalin',
    preparation_temperature: '',
    processing_time_value: '10 minutes',
    processing_time_unit: '',
    storage_medium: 'Paraffin',
    storage_temperature: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'millimeter',
    section_index_number: 2,
    area_value: 15.84,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 6,
    sample_ID: 'Visium_10CC_A2_S3',
    source_storage_time_value: '86 day',
    source_storage_time_unit: '',
    preparation_medium: 'Formalin',
    preparation_temperature: '',
    processing_time_value: '10 minutes',
    processing_time_unit: '',
    storage_medium: 'Paraffin',
    storage_temperature: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'millimeter',
    section_index_number: '',
    area_value: '',
    area_unit: '',
    notes: '',
  },
  {
    _id: 7,
    sample_ID: 'Visium_10CC_A2_S4',
    source_storage_time_value: '86 day',
    source_storage_time_unit: '',
    preparation_medium: 'Formalin',
    preparation_temperature: '',
    processing_time_value: '10 minutes',
    processing_time_unit: '',
    storage_medium: 'Paraffin',
    storage_temperature: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'millimeter',
    section_index_number: '',
    area_value: '',
    area_unit: '',
    notes: '',
  },
  {
    _id: 8,
    sample_ID: 'Visium_10CC_A2_S5',
    source_storage_time_value: '86 day',
    source_storage_time_unit: '',
    preparation_medium: 'Formalin',
    preparation_temperature: '',
    processing_time_value: '10 minutes',
    processing_time_unit: '',
    storage_medium: 'Paraffin',
    storage_temperature: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'millimeter',
    section_index_number: 5,
    area_value: 12.04,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 9,
    sample_ID: 'Visium_40AZ_Q9_S1',
    source_storage_time_value: 100,
    source_storage_time_unit: 'd',
    preparation_medium: 'Fresh frozen OCT',
    preparation_temperature: '-80 C',
    processing_time_value: 5,
    processing_time_unit: 'minute',
    storage_medium: 'OCT Embedded',
    storage_temperature: '-80 C',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 8,
    thickness_unit: '',
    section_index_number: 1,
    area_value: '',
    area_unit: '',
    notes: '',
  },
  {
    _id: 10,
    sample_ID: 'Visium_40AZ_Q9_S2',
    source_storage_time_value: 100,
    source_storage_time_unit: 'd',
    preparation_medium: 'Fresh frozen OCT',
    preparation_temperature: '-80 C',
    processing_time_value: 5,
    processing_time_unit: 'minute',
    storage_medium: 'OCT Embedded',
    storage_temperature: '-80 C',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 8,
    thickness_unit: '',
    section_index_number: 2,
    area_value: '',
    area_unit: '',
    notes: '',
  },
  {
    _id: 11,
    sample_ID: 'Visium_40AZ_Q9_S3',
    source_storage_time_value: 100,
    source_storage_time_unit: 'd',
    preparation_medium: 'Fresh frozen OCT',
    preparation_temperature: '-80 C',
    processing_time_value: 5,
    processing_time_unit: 'minute',
    storage_medium: 'OCT Embedded',
    storage_temperature: '-80 C',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 8,
    thickness_unit: '',
    section_index_number: 3,
    area_value: '',
    area_unit: '',
    notes: '',
  },
  {
    _id: 12,
    sample_ID: 'Visium_40AZ_Q9_S4',
    source_storage_time_value: 100,
    source_storage_time_unit: 'd',
    preparation_medium: 'Fresh frozen OCT',
    preparation_temperature: '-80 C',
    processing_time_value: 5,
    processing_time_unit: 'minute',
    storage_medium: 'OCT Embedded',
    storage_temperature: '-80 C',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 8,
    thickness_unit: '',
    section_index_number: 4,
    area_value: '',
    area_unit: '',
    notes: '',
  },
  {
    _id: 13,
    sample_ID: 'Visium_90LC_W3_S1',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '',
    processing_time_value: 3,
    processing_time_unit: 'minute',
    storage_medium: 'OCT',
    storage_temperature: '4 Celcius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 2,
    thickness_unit: 'millimeter',
    section_index_number: 4,
    area_value: 5.65,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 14,
    sample_ID: 'Visium_90LC_W3_S2',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '',
    processing_time_value: 3,
    processing_time_unit: 'minute',
    storage_medium: 'OCT',
    storage_temperature: '4 Celcius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 2,
    thickness_unit: 'millimeter',
    section_index_number: 5,
    area_value: 3.45,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 15,
    sample_ID: 'Visium_90LC_W3_S3',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '',
    processing_time_value: 3,
    processing_time_unit: 'minute',
    storage_medium: 'OCT',
    storage_temperature: '4 Celcius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 2,
    thickness_unit: 'millimeter',
    section_index_number: 6,
    area_value: 7.54,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 16,
    sample_ID: 'Visium_90LC_W3_S4',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '',
    processing_time_value: 3,
    processing_time_unit: 'minute',
    storage_medium: 'OCT',
    storage_temperature: '4 Celcius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 2,
    thickness_unit: 'millimeter',
    section_index_number: 7,
    area_value: 6.09,
    area_unit: 'mm^2',
    notes: '',
  },
  {
    _id: 17,
    sample_ID: 'Visium_90LC_W3_S5',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'Unknown',
    storage_temperature: 'Liquid Nitrogen',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 20,
    thickness_unit: 'mm',
    section_index_number: 1,
    area_value: '26.76 square mm',
    area_unit: '',
    notes: '',
  },
  {
    _id: 18,
    sample_ID: 'Visium_90LC_W3_S6',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'Unknown',
    storage_temperature: 'Liquid Nitrogen',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 20,
    thickness_unit: 'mm',
    section_index_number: 2,
    area_value: '27.89 square mm',
    area_unit: '',
    notes: '',
  },
  {
    _id: 19,
    sample_ID: 'Visium_90LC_W3_S7',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol',
    preparation_temperature: '',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'Unknown',
    storage_temperature: 'Liquid Nitrogen',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 20,
    thickness_unit: 'mm',
    section_index_number: 3,
    area_value: '30.23 square mm',
    area_unit: '',
    notes: '',
  },
];

export const ERROR_REPORT = [
  {
    row: 0,
    column: 'processing_time_unit',
    value: 'min',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 1,
    column: 'processing_time_unit',
    value: 'min',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 2,
    column: 'processing_time_unit',
    value: 'min',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 3,
    column: 'processing_time_unit',
    value: 'min',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 4,
    column: 'source_storage_time_value',
    value: '86 day',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 5,
    column: 'source_storage_time_value',
    value: '86 day',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 6,
    column: 'source_storage_time_value',
    value: '86 day',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 7,
    column: 'source_storage_time_value',
    value: '86 day',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 8,
    column: 'source_storage_time_value',
    value: '86 day',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 4,
    column: 'source_storage_time_unit',
    errorType: 'missingRequired',
  }, {
    row: 5,
    column: 'source_storage_time_unit',
    errorType: 'missingRequired',
  }, {
    row: 6,
    column: 'source_storage_time_unit',
    errorType: 'missingRequired',
  }, {
    row: 7,
    column: 'source_storage_time_unit',
    errorType: 'missingRequired',
  }, {
    row: 8,
    column: 'source_storage_time_unit',
    errorType: 'missingRequired',
  }, {
    row: 4,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Buffered Formalin (10% NBF)',
    errorType: 'notStandardTerm',
  }, {
    row: 5,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Buffered Formalin (10% NBF)',
    errorType: 'notStandardTerm',
  }, {
    row: 6,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Buffered Formalin (10% NBF)',
    errorType: 'notStandardTerm',
  }, {
    row: 7,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Buffered Formalin (10% NBF)',
    errorType: 'notStandardTerm',
  }, {
    row: 8,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Buffered Formalin (10% NBF)',
    errorType: 'notStandardTerm',
  }, {
    row: 4,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 5,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 6,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 7,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 8,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 4,
    column: 'storage_medium',
    value: 'Paraffin',
    suggestion: 'Paraffin Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 5,
    column: 'storage_medium',
    value: 'Paraffin',
    suggestion: 'Paraffin Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 6,
    column: 'storage_medium',
    value: 'Paraffin',
    suggestion: 'Paraffin Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 7,
    column: 'storage_medium',
    value: 'Paraffin',
    suggestion: 'Paraffin Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 8,
    column: 'storage_medium',
    value: 'Paraffin',
    suggestion: 'Paraffin Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 4,
    column: 'storage_temperature',
    errorType: 'missingRequired',
  }, {
    row: 5,
    column: 'storage_temperature',
    errorType: 'missingRequired',
  }, {
    row: 6,
    column: 'storage_temperature',
    errorType: 'missingRequired',
  }, {
    row: 7,
    column: 'storage_temperature',
    errorType: 'missingRequired',
  }, {
    row: 8,
    column: 'storage_temperature',
    errorType: 'missingRequired',
  }, {
    row: 0,
    column: 'thickness_unit',
    value: '_m',
    suggestion: 'millimeter',
    errorType: 'notStandardTerm',
  }, {
    row: 1,
    column: 'thickness_unit',
    value: '_m',
    suggestion: 'millimeter',
    errorType: 'notStandardTerm',
  }, {
    row: 2,
    column: 'thickness_unit',
    value: '_m',
    suggestion: 'millimeter',
    errorType: 'notStandardTerm',
  }, {
    row: 3,
    column: 'thickness_unit',
    value: '_m',
    suggestion: 'millimeter',
    errorType: 'notStandardTerm',
  }, {
    row: 6,
    column: 'section_index_number',
    errorType: 'missingRequired',
  }, {
    row: 7,
    column: 'section_index_number',
    errorType: 'missingRequired',
  }, {
    row: 6,
    column: 'area_value',
    errorType: 'missingRequired',
  }, {
    row: 7,
    column: 'area_value',
    errorType: 'missingRequired',
  }, {
    row: 9,
    column: 'source_storage_time_unit',
    value: 'd',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 10,
    column: 'source_storage_time_unit',
    value: 'd',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 11,
    column: 'source_storage_time_unit',
    value: 'd',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 12,
    column: 'source_storage_time_unit',
    value: 'd',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 9,
    column: 'storage_temperature',
    value: '-80 C',
    suggestion: '-80 Celsius (Unspecified)',
    errorType: 'notStandardTerm',
  }, {
    row: 10,
    column: 'storage_temperature',
    value: '-80 C',
    suggestion: '-80 Celsius (Unspecified)',
    errorType: 'notStandardTerm',
  }, {
    row: 11,
    column: 'storage_temperature',
    value: '-80 C',
    suggestion: '-80 Celsius (Unspecified)',
    errorType: 'notStandardTerm',
  }, {
    row: 12,
    column: 'storage_temperature',
    value: '-80 C',
    suggestion: '-80 Celsius (Unspecified)',
    errorType: 'notStandardTerm',
  }, {
    row: 9,
    column: 'preparation_temperature',
    value: '-80 C',
    suggestion: 'Minus 80 Degrees Celsius',
    errorType: 'notStandardTerm',
  }, {
    row: 10,
    column: 'preparation_temperature',
    value: '-80 C',
    suggestion: 'Minus 80 Degrees Celsius',
    errorType: 'notStandardTerm',
  }, {
    row: 11,
    column: 'preparation_temperature',
    value: '-80 C',
    suggestion: 'Minus 80 Degrees Celsius',
    errorType: 'notStandardTerm',
  }, {
    row: 12,
    column: 'preparation_temperature',
    value: '-80 C',
    suggestion: 'Minus 80 Degrees Celsius',
    errorType: 'notStandardTerm',
  }, {
    row: 9,
    column: 'thickness_unit',
    errorType: 'missingRequired',
  }, {
    row: 10,
    column: 'thickness_unit',
    errorType: 'missingRequired',
  }, {
    row: 11,
    column: 'thickness_unit',
    errorType: 'missingRequired',
  }, {
    row: 12,
    column: 'thickness_unit',
    errorType: 'missingRequired',
  }, {
    row: 9,
    column: 'area_value',
    errorType: 'missingRequired',
  }, {
    row: 10,
    column: 'area_value',
    errorType: 'missingRequired',
  }, {
    row: 11,
    column: 'area_value',
    errorType: 'missingRequired',
  }, {
    row: 12,
    column: 'area_value',
    errorType: 'missingRequired',
  }, {
    row: 13,
    column: 'preparation_temperature',
    errorType: 'missingRequired',
  }, {
    row: 14,
    column: 'preparation_temperature',
    errorType: 'missingRequired',
  }, {
    row: 15,
    column: 'preparation_temperature',
    errorType: 'missingRequired',
  }, {
    row: 16,
    column: 'preparation_temperature',
    errorType: 'missingRequired',
  }, {
    row: 17,
    column: 'preparation_temperature',
    errorType: 'missingRequired',
  }, {
    row: 18,
    column: 'preparation_temperature',
    errorType: 'missingRequired',
  }, {
    row: 19,
    column: 'preparation_temperature',
    errorType: 'missingRequired',
  }, {
    row: 13,
    column: 'storage_medium',
    value: 'OCT',
    suggestion: 'OCT Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 14,
    column: 'storage_medium',
    value: 'OCT',
    suggestion: 'OCT Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 15,
    column: 'storage_medium',
    value: 'OCT',
    suggestion: 'OCT Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 16,
    column: 'storage_medium',
    value: 'OCT',
    suggestion: 'OCT Embedded',
    errorType: 'notStandardTerm',
  }, {
    row: 17,
    column: 'thickness_unit',
    value: 'mm',
    suggestion: 'millimeter',
    errorType: 'notStandardTerm',
  }, {
    row: 18,
    column: 'thickness_unit',
    value: 'mm',
    suggestion: 'millimeter',
    errorType: 'notStandardTerm',
  }, {
    row: 19,
    column: 'thickness_unit',
    value: 'mm',
    suggestion: 'millimeter',
    errorType: 'notStandardTerm',
  }, {
    row: 17,
    column: 'area_value',
    value: '26.76 square mm',
    suggestion: 26.76,
    errorType: 'notNumberType',
  }, {
    row: 18,
    column: 'area_value',
    value: '27.89 square mm',
    suggestion: 27.89,
    errorType: 'notNumberType',
  }, {
    row: 19,
    column: 'area_value',
    value: '30.23 square mm',
    suggestion: 30.23,
    errorType: 'notNumberType',
  },
];

export const APP_DATA = {
  schema: METADATA_SCHEMA,
  data: METADATA_RECORDS,
  reporting: ERROR_REPORT,
};
