export const METADATA_SCHEMA = {
  title: 'Tissue Block',
  columns: {
    sample_ID: {
      name: 'sample_ID',
      label: 'Sample ID',
      type: 'text',
      required: true,
      permissibleValues: [],
      description: 'The HuBMAP ID for the sample assigned by the ingest portal. An example value might be "HBM743.CKJW.876".',
    },
    source_storage_time_value: {
      name: 'source_storage_time_value',
      label: 'Source Storage Time Value',
      type: 'number',
      required: true,
      permissibleValues: [],
      description: 'How long was the source material stored, prior to this sample being processed? For tissue blocks, this would typically be the time between when the organ arrived in the lab and the processing of the organ began. In most cases this will likely be 0, while in some cases the organ might be stored (on ice) in the lab before dissection. For tissue sections, this would be how long the tissue block was stored, usually in a -80 freezer, prior to the section being cut. For suspensions, this would be the length of time the tissue block was stored prior to the initiation of the dissociation process.',
    },
    source_storage_time_unit: {
      name: 'source_storage_time_unit',
      label: 'Source Storage Time Unit',
      type: 'text',
      permissibleValues: [{
        label: 'minute',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000031',
      }, {
        label: 'hour',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000032',
      }, {
        label: 'day',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000032',
      }, {
        label: 'year',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000036',
      }],
      required: true,
      description: 'Time unit',
    },
    preparation_medium: {
      name: 'preparation_medium',
      label: 'Preparation Medium',
      type: 'text',
      permissibleValues: [
        { label: 'PFA (4%)', meaning: '' },
        { label: 'Buffered formalin (10% NBF)', meaning: '' },
        { label: 'Non-buffered formalin (FOR)', meaning: '' },
        { label: '1 x PBS', meaning: '' },
        { label: 'Formalin fixed OCT', meaning: '' },
        { label: 'PFA fixed frozen OCT', meaning: '' },
        { label: 'Fresh frozen OCT', meaning: '' },
        { label: 'Fresh frozen CMC', meaning: '' },
        { label: 'MACS tissue storage solution', meaning: '' },
        { label: 'RNAlater', meaning: '' },
        { label: 'Methanol (100%)', meaning: '' },
        { label: 'Non-aldehyde based without acetic acid (NAA)', meaning: '' },
        { label: 'Non-aldehyde with acetic acid (ACA)', meaning: '' },
        { label: 'PAXgene tissue kit (PXT)', meaning: '' },
        { label: 'Allprotect tissue reagent (ALL)', meaning: '' },
        { label: 'CLARITY hydrogel', meaning: '' },
        { label: 'Agarose inflated', meaning: '' },
        { label: 'Alginate inflated', meaning: '' },
        { label: 'None', meaning: '' },
        { label: 'Unknown', meaning: '' }],
      required: true,
      description: 'The medium used during preparation of the sample.',
    },
    preparation_condition: {
      name: 'preparation_condition',
      label: 'Preparation Condition',
      type: 'text',
      permissibleValues: [
        { label: 'Liquid nitrogen', meaning: '' },
        { label: 'Liquid nitrogen vapor', meaning: '' },
        { label: 'Dry ice', meaning: '' },
        { label: '-80 celsius', meaning: '' },
        { label: '-20 celsius', meaning: '' },
        { label: '4 celsius', meaning: '' },
        { label: '37 celsius', meaning: '' },
        { label: 'Unknown', meaning: '' }],
      required: true,
      description: 'The condition under which the preparation occured, such as the temperature.',
    },
    processing_time_value: {
      name: 'processing_time_value',
      label: 'Processing Time Value',
      type: 'number',
      required: true,
      permissibleValues: [],
      description: 'How long was the tissue being handled before the initial preservation? For tissue blocks, this would typically be the length of time from when the organ was received in the lab to when the tissue block is frozen or otherwise preserved (e.g., imbedded in OCT). For a tissue section this would be how long it takes to slice the tissue block and fix the mounted slice, after removing the tissue block from the freezer. For a suspension this would be the length of time from when the tissue block is removed from the freezer, dissociated and processed to the point where by the suspension is put into the initial preservation buffer.',
    },
    processing_time_unit: {
      name: 'processing_time_unit',
      label: 'Processing Time Unit',
      type: 'text',
      permissibleValues: [{
        label: 'minute',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000031',
      }, {
        label: 'hour',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000032',
      }, {
        label: 'day',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000032',
      }],
      required: true,
      description: 'Time unit.',
    },
    storage_medium: {
      name: 'storage_medium',
      label: 'Storage Medium',
      type: 'text',
      permissibleValues: [
        { label: 'PFA (4%)', meaning: '' },
        { label: 'Buffered formalin (10% NBF)', meaning: '' },
        { label: 'Non-buffered formalin (FOR)', meaning: '' },
        { label: '1 x PBS', meaning: '' },
        { label: 'PBS + 0.05% Azide', meaning: '' },
        { label: 'Antifreeze (50% PBS + 50% Glycerol + 0.05% Azide)', meaning: '' },
        { label: 'OCT embedded', meaning: '' },
        { label: 'CMC embedded', meaning: '' },
        { label: 'OCT embedded cryoprotected (sucrose)', meaning: '' },
        { label: 'Paraffin embedded', meaning: '' },
        { label: 'MACS tissue storage solution', meaning: '' },
        { label: 'RNAlater', meaning: '' },
        { label: 'Methanol (80%)', meaning: '' },
        { label: 'Tris-EDTA', meaning: '' },
        { label: 'Ethanol (70%)', meaning: '' },
        { label: '90% Serum + 10% DMSO', meaning: '' },
        { label: 'DMSO (no serum)', meaning: '' },
        { label: 'PAXgene tissue kit (PXT)', meaning: '' },
        { label: 'Allprotect tissue reagent (ALL)', meaning: '' },
        { label: 'Sucrose cryoprotection solution', meaning: '' },
        { label: 'Carboxymethylcellulose (CMC)', meaning: '' },
        { label: 'None', meaning: '' },
        { label: 'Unknown', meaning: '' }],
      required: true,
      description: 'What was the sample preserved in.',
    },
    storage_condition: {
      name: 'storage_condition',
      label: 'Storage Condition',
      type: 'text',
      permissibleValues: [
        { label: 'Liquid nitrogen in unspecified container', meaning: '' },
        { label: 'Liquid nitrogen in cryotube', meaning: '' },
        { label: 'Liquid nitrogen in straw', meaning: '' },
        { label: 'Liquid nitrogen vapor', meaning: '' },
        { label: 'Dry ice', meaning: '' },
        { label: '-80 celsius in unspecified container', meaning: '' },
        { label: '-80 celsius in cryotube', meaning: '' },
        { label: '-80 celsius in straw', meaning: '' },
        { label: '-20 celsius', meaning: '' },
        { label: '4 celsius', meaning: '' },
        { label: '24 celsius (room temperature)', meaning: '' },
        { label: '37 celsius', meaning: '' },
        { label: 'None', meaning: '' },
        { label: 'Unknown', meaning: '' }],
      required: true,
      description: 'The condition under which the sample is stored, after preparation and before the assay is performed.',
    },
    quality_criteria: {
      name: 'quality_criteria',
      label: 'Quality Criteria',
      type: 'text',
      required: false,
      permissibleValues: [],
      description: 'For example, RIN: 8.7. For suspensions, measured by visual inspection prior to cell lysis or defined by known parameters such as wells with several cells or no cells. This can be captured at a high level. "OK" or "not OK", or with more specificity such as "debris", "clump", "low clump".',
    },
    histological_report: {
      name: 'histological_report',
      label: 'Histological Report',
      type: 'text',
      required: false,
      permissibleValues: [],
      description: 'histopathological reporting of key variables that are important for the tissue (absence of necrosis, comment on composition, significant pathology description, high level inflammation/fibrosis assessment, etc.)',
    },
    thickness_value: {
      name: 'thickness_value',
      label: 'Thickness Value',
      type: 'number',
      required: true,
      permissibleValues: [],
      description: 'Thickness of a tissue section',
    },
    thickness_unit: {
      name: 'thickness_unit',
      label: 'Thickness Unit',
      type: 'text',
      permissibleValues: [{
        label: 'micrometer',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000017',
      }, {
        label: 'millimeter',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000016',
      }, {
        label: 'centimeter',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000015',
      }],
      required: true,
      description: 'Thickness unit',
    },
    section_index_number: {
      name: 'section_index_number',
      label: 'Section Index Number',
      type: 'number',
      required: true,
      permissibleValues: [],
      description: 'The index number for the section if the sample is a single section.',
    },
    area_value: {
      name: 'area_value',
      label: 'Area Value',
      type: 'number',
      required: false,
      permissibleValues: [],
      description: 'The area of a tissue section.',
    },
    area_unit: {
      name: 'area_unit',
      label: 'Area Unit',
      type: 'text',
      permissibleValues: [{
        label: 'mm^2',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000082',
      }, {
        label: 'um^2',
        meaning: 'http://purl.obolibrary.org/obo/UO_0000082',
      }],
      required: false,
      description: 'Area unit',
    },
    notes: {
      name: 'notes',
      label: 'Notes',
      type: 'text',
      required: false,
      permissibleValues: [],
      description: 'Researcher note',
    },
  },
};

export const METADATA_RECORDS = [
  {
    rowNumber: 0,
    sample_ID: 'Visium_9OLC_A4_S1',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'OCT embedded',
    storage_condition: '-80 celsius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: 2,
    area_value: 12.24,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 1,
    sample_ID: 'Visium_9OLC_A4_S2',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'OCT embedded',
    storage_condition: '-80 celsius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: 3,
    area_value: 11.68,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 2,
    sample_ID: 'Visium_9OLC_I4_S1',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'OCT embedded',
    storage_condition: '-80 celsius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: 2,
    area_value: 17.42,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 3,
    sample_ID: 'Visium_9OLC_I4_S2',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'OCT embedded',
    storage_condition: '-80 celsius',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: 3,
    area_value: 15.84,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 4,
    sample_ID: '',
    source_storage_time_value: '86 days',
    source_storage_time_unit: 'days',
    preparation_medium: 'Formalin',
    preparation_condition: '',
    processing_time_value: '10 minutes',
    processing_time_unit: 'minutes',
    storage_medium: 'Paraffin embedded',
    storage_condition: 'Liquid nitrogen',
    quality_criteria: '',
    histological_report: 12.05,
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: 1,
    area_value: 12.05,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 5,
    sample_ID: '',
    source_storage_time_value: '86 days',
    source_storage_time_unit: 'days',
    preparation_medium: 'Formalin',
    preparation_condition: '',
    processing_time_value: '10 minutes',
    processing_time_unit: 'minutes',
    storage_medium: 'Paraffin embedded',
    storage_condition: 'Liquid nitrogen',
    quality_criteria: '',
    histological_report: 15.84,
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: 2,
    area_value: 15.84,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 6,
    sample_ID: '',
    source_storage_time_value: '86 days',
    source_storage_time_unit: 'days',
    preparation_medium: 'Formalin',
    preparation_condition: '',
    processing_time_value: '10 minutes',
    processing_time_unit: 'minutes',
    storage_medium: 'Paraffin embedded',
    storage_condition: 'Liquid nitrogen',
    quality_criteria: '',
    histological_report: 15.21,
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: '',
    area_value: 15.21,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 7,
    sample_ID: '',
    source_storage_time_value: '86 days',
    source_storage_time_unit: 'days',
    preparation_medium: 'Formalin',
    preparation_condition: '',
    processing_time_value: '10 minutes',
    processing_time_unit: 'minutes',
    storage_medium: 'Paraffin embedded',
    storage_condition: 'Liquid nitrogen',
    quality_criteria: '',
    histological_report: 16.34,
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: '',
    area_value: 16.34,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 8,
    sample_ID: '',
    source_storage_time_value: '86 days',
    source_storage_time_unit: 'days',
    preparation_medium: 'Formalin',
    preparation_condition: '',
    processing_time_value: '10 minutes',
    processing_time_unit: 'minutes',
    storage_medium: 'Paraffin embedded',
    storage_condition: 'Liquid nitrogen',
    quality_criteria: '',
    histological_report: 12.04,
    thickness_value: 10,
    thickness_unit: 'mm',
    section_index_number: 5,
    area_value: 12.04,
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 9,
    sample_ID: 'Visium_40AZ_Q9_S1',
    source_storage_time_value: 100,
    source_storage_time_unit: 'd',
    preparation_medium: 'Agar-agar',
    preparation_condition: '',
    processing_time_value: 5,
    processing_time_unit: 'min',
    storage_medium: 'OCT embedded',
    storage_condition: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 8,
    thickness_unit: 'mm',
    section_index_number: 1,
    area_value: '',
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 10,
    sample_ID: 'Visium_40AZ_Q9_S2',
    source_storage_time_value: 100,
    source_storage_time_unit: 'd',
    preparation_medium: 'Agar-agar',
    preparation_condition: '',
    processing_time_value: 5,
    processing_time_unit: 'min',
    storage_medium: 'OCT embedded',
    storage_condition: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 8,
    thickness_unit: 'mm',
    section_index_number: 2,
    area_value: '',
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 11,
    sample_ID: 'Visium_40AZ_Q9_S3',
    source_storage_time_value: 100,
    source_storage_time_unit: 'd',
    preparation_medium: 'Agar-agar',
    preparation_condition: '',
    processing_time_value: 5,
    processing_time_unit: 'min',
    storage_medium: 'OCT embedded',
    storage_condition: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 8,
    thickness_unit: 'mm',
    section_index_number: 3,
    area_value: '',
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 12,
    sample_ID: 'Visium_40AZ_Q9_S4',
    source_storage_time_value: 100,
    source_storage_time_unit: 'd',
    preparation_medium: 'Agar-agar',
    preparation_condition: '',
    processing_time_value: 5,
    processing_time_unit: 'min',
    storage_medium: 'OCT embedded',
    storage_condition: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 8,
    thickness_unit: 'mm',
    section_index_number: 4,
    area_value: '',
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 13,
    sample_ID: 'Visium_90LC_W3_S1',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 3,
    processing_time_unit: 'minute',
    storage_medium: 'Methanol (80%)',
    storage_condition: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 2,
    thickness_unit: 'mm',
    section_index_number: '',
    area_value: '5.65 square mm',
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 14,
    sample_ID: 'Visium_90LC_W3_S2',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 3,
    processing_time_unit: 'minute',
    storage_medium: 'Methanol (80%)',
    storage_condition: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 2,
    thickness_unit: 'mm',
    section_index_number: '',
    area_value: '3.45 square mm',
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 15,
    sample_ID: 'Visium_90LC_W3_S3',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 3,
    processing_time_unit: 'minute',
    storage_medium: 'Methanol (80%)',
    storage_condition: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 2,
    thickness_unit: 'mm',
    section_index_number: '',
    area_value: '7.54 square mm',
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 16,
    sample_ID: 'Visium_90LC_W3_S4',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 3,
    processing_time_unit: 'minute',
    storage_medium: 'Methanol (80%)',
    storage_condition: '',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 2,
    thickness_unit: 'mm',
    section_index_number: '',
    area_value: '6.09 square mm',
    area_unit: 'mm^2',
    notes: '',
  }, {
    rowNumber: 17,
    sample_ID: 'Visium_90LC_W3_S5',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'Unknown',
    storage_condition: 'Liquid nitrogen',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 20,
    thickness_unit: 'mm',
    section_index_number: 5,
    area_value: '',
    area_unit: '',
    notes: '',
  }, {
    rowNumber: 18,
    sample_ID: 'Visium_90LC_W3_S6',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'Unknown',
    storage_condition: 'Liquid nitrogen',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 20,
    thickness_unit: 'mm',
    section_index_number: 6,
    area_value: '',
    area_unit: '',
    notes: '',
  }, {
    rowNumber: 19,
    sample_ID: 'Visium_90LC_W3_S7',
    source_storage_time_value: 208,
    source_storage_time_unit: 'day',
    preparation_medium: 'Methanol (100%)',
    preparation_condition: '-20 celsius',
    processing_time_value: 4,
    processing_time_unit: 'minute',
    storage_medium: 'Unknown',
    storage_condition: 'Liquid nitrogen',
    quality_criteria: '',
    histological_report: '',
    thickness_value: 20,
    thickness_unit: 'mm',
    section_index_number: 7,
    area_value: '',
    area_unit: '',
    notes: '',
  }];

export const ERROR_REPORT = [
  {
    row: 4,
    column: 'sample_ID',
    errorType: 'missingRequired',
  }, {
    row: 5,
    column: 'sample_ID',
    errorType: 'missingRequired',
  }, {
    row: 6,
    column: 'sample_ID',
    errorType: 'missingRequired',
  }, {
    row: 7,
    column: 'sample_ID',
    errorType: 'missingRequired',
  }, {
    row: 8,
    column: 'sample_ID',
    errorType: 'missingRequired',
  }, {
    row: 4,
    column: 'source_storage_time_value',
    value: '86 days',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 5,
    column: 'source_storage_time_value',
    value: '86 days',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 6,
    column: 'source_storage_time_value',
    value: '86 days',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 7,
    column: 'source_storage_time_value',
    value: '86 days',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 8,
    column: 'source_storage_time_value',
    value: '86 days',
    suggestion: 86,
    errorType: 'notNumberType',
  }, {
    row: 4,
    column: 'source_storage_time_unit',
    value: 'days',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 5,
    column: 'source_storage_time_unit',
    value: 'days',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 6,
    column: 'source_storage_time_unit',
    value: 'days',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 7,
    column: 'source_storage_time_unit',
    value: 'days',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 8,
    column: 'source_storage_time_unit',
    value: 'days',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 9,
    column: 'source_storage_time_unit',
    value: 'd',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 10,
    column: 'source_storage_time_unit',
    value: 'd',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 11,
    column: 'source_storage_time_unit',
    value: 'd',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 12,
    column: 'source_storage_time_unit',
    value: 'd',
    suggestion: 'day',
    errorType: 'notStandardTerm',
  }, {
    row: 4,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Formalin fixed OCT',
    errorType: 'notStandardTerm',
  }, {
    row: 5,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Formalin fixed OCT',
    errorType: 'notStandardTerm',
  }, {
    row: 6,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Formalin fixed OCT',
    errorType: 'notStandardTerm',
  }, {
    row: 7,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Formalin fixed OCT',
    errorType: 'notStandardTerm',
  }, {
    row: 8,
    column: 'preparation_medium',
    value: 'Formalin',
    suggestion: 'Formalin fixed OCT',
    errorType: 'notStandardTerm',
  }, {
    row: 9,
    column: 'preparation_medium',
    value: 'Agar-agar',
    suggestion: null,
    errorType: 'notStandardTerm',
  }, {
    row: 10,
    column: 'preparation_medium',
    value: 'Agar-agar',
    suggestion: null,
    errorType: 'notStandardTerm',
  }, {
    row: 11,
    column: 'preparation_medium',
    value: 'Agar-agar',
    suggestion: null,
    errorType: 'notStandardTerm',
  }, {
    row: 12,
    column: 'preparation_medium',
    value: 'Agar-agar',
    suggestion: null,
    errorType: 'notStandardTerm',
  }, {
    row: 4,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 5,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 6,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 7,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 8,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 9,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 10,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 11,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 12,
    column: 'preparation_condition',
    errorType: 'missingRequired',
  }, {
    row: 4,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 5,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 6,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 7,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 8,
    column: 'processing_time_value',
    value: '10 minutes',
    suggestion: 10,
    errorType: 'notNumberType',
  }, {
    row: 4,
    column: 'processing_time_unit',
    value: 'minutes',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 5,
    column: 'processing_time_unit',
    value: 'minutes',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 6,
    column: 'processing_time_unit',
    value: 'minutes',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 7,
    column: 'processing_time_unit',
    value: 'minutes',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 8,
    column: 'processing_time_unit',
    value: 'minutes',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 9,
    column: 'processing_time_unit',
    value: 'min',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 10,
    column: 'processing_time_unit',
    value: 'min',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 11,
    column: 'processing_time_unit',
    value: 'min',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 12,
    column: 'processing_time_unit',
    value: 'min',
    suggestion: 'minute',
    errorType: 'notStandardTerm',
  }, {
    row: 9,
    column: 'storage_condition',
    errorType: 'missingRequired',
  }, {
    row: 10,
    column: 'storage_condition',
    errorType: 'missingRequired',
  }, {
    row: 11,
    column: 'storage_condition',
    errorType: 'missingRequired',
  }, {
    row: 12,
    column: 'storage_condition',
    errorType: 'missingRequired',
  }, {
    row: 13,
    column: 'storage_condition',
    errorType: 'missingRequired',
  }, {
    row: 14,
    column: 'storage_condition',
    errorType: 'missingRequired',
  }, {
    row: 15,
    column: 'storage_condition',
    errorType: 'missingRequired',
  }, {
    row: 16,
    column: 'storage_condition',
    errorType: 'missingRequired',
  }, {
    row: 4,
    column: 'histological_report',
    value: '12.05',
    suggestion: '',
    errorType: 'notStringType',
  }, {
    row: 5,
    column: 'histological_report',
    value: '15.84',
    suggestion: '',
    errorType: 'notStringType',
  }, {
    row: 6,
    column: 'histological_report',
    value: '15.21',
    suggestion: '',
    errorType: 'notStringType',
  }, {
    row: 7,
    column: 'histological_report',
    value: '16.34',
    suggestion: '',
    errorType: 'notStringType',
  }, {
    row: 8,
    column: 'histological_report',
    value: '12.04',
    suggestion: '',
    errorType: 'notStringType',
  }, {
    row: 6,
    column: 'section_index_number',
    errorType: 'missingRequired',
  }, {
    row: 7,
    column: 'section_index_number',
    errorType: 'missingRequired',
  }, {
    row: 13,
    column: 'section_index_number',
    errorType: 'missingRequired',
  }, {
    row: 14,
    column: 'section_index_number',
    errorType: 'missingRequired',
  }, {
    row: 15,
    column: 'section_index_number',
    errorType: 'missingRequired',
  }, {
    row: 16,
    column: 'section_index_number',
    errorType: 'missingRequired',
  }, {
    row: 13,
    column: 'area_value',
    value: '5.65 square mm',
    suggestion: 5.65,
    errorType: 'notNumberType',
  }, {
    row: 14,
    column: 'area_value',
    value: '3.45 square mm',
    suggestion: 3.45,
    errorType: 'notNumberType',
  }, {
    row: 15,
    column: 'area_value',
    value: '7.54 square mm',
    suggestion: 7.54,
    errorType: 'notNumberType',
  }, {
    row: 16,
    column: 'area_value',
    value: '6.09 square mm',
    suggestion: 6.09,
    errorType: 'notNumberType',
  },
];

export const APP_DATA = {
  schema: METADATA_SCHEMA,
  data: METADATA_RECORDS,
  reporting: ERROR_REPORT,
};
